// GENERATED by generators/android.mjs. Do not edit. Source: tokens/tokens.json
package com.astro.design.tokens

import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp

// Font-resource independent text style data. Map fontWeight to your own
// FontWeight and fontFamily at the call site.
data class AstroTextStyle(
    val fontSizeSp: TextUnit,
    val lineHeightSp: TextUnit,
    val fontWeight: Int,
    val letterSpacingSp: TextUnit
)

object AstroTypography {
    val displayHuge: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 42.sp,
        lineHeightSp = 48.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.3f).sp
    )
    val displayLarge: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 36.sp,
        lineHeightSp = 42.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.3f).sp
    )
    val displaySmall: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 30.sp,
        lineHeightSp = 36.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.3f).sp
    )
    val displayTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 24.sp,
        lineHeightSp = 30.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.3f).sp
    )
    val headlineLarge: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 20.sp,
        lineHeightSp = 28.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.2f).sp
    )
    val headlineDefault: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 18.sp,
        lineHeightSp = 26.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.2f).sp
    )
    val headlineSmall: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 16.sp,
        lineHeightSp = 24.sp,
        fontWeight = 800,
        letterSpacingSp = (-0.2f).sp
    )
    val headlineTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 14.sp,
        lineHeightSp = 20.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.1f).sp
    )
    val headlineSuperTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 16.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.3f).sp
    )
    val bodyLarge: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 18.sp,
        lineHeightSp = 24.sp,
        fontWeight = 600,
        letterSpacingSp = (-0.2f).sp
    )
    val bodyLargeStrong: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 18.sp,
        lineHeightSp = 24.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.2f).sp
    )
    val bodyDefault: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 16.sp,
        lineHeightSp = 22.sp,
        fontWeight = 600,
        letterSpacingSp = 0f.sp
    )
    val bodyDefaultStrong: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 16.sp,
        lineHeightSp = 22.sp,
        fontWeight = 700,
        letterSpacingSp = 0f.sp
    )
    val bodySmall: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 14.sp,
        lineHeightSp = 20.sp,
        fontWeight = 600,
        letterSpacingSp = (-0.1f).sp
    )
    val bodySmallStrong: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 14.sp,
        lineHeightSp = 20.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.1f).sp
    )
    val bodyTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 16.sp,
        fontWeight = 600,
        letterSpacingSp = (-0.3f).sp
    )
    val bodyTinyStrong: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 16.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.3f).sp
    )
    val paragraphLarge: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 18.sp,
        lineHeightSp = 26.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val paragraphDefault: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 16.sp,
        lineHeightSp = 24.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val paragraphSmall: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 14.sp,
        lineHeightSp = 22.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val paragraphTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 18.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val captionDefault: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 14.sp,
        lineHeightSp = 20.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val captionSmall: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 16.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val captionTiny: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 10.sp,
        lineHeightSp = 12.sp,
        fontWeight = 400,
        letterSpacingSp = 0f.sp
    )
    val captionTinyBold: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 10.sp,
        lineHeightSp = 12.sp,
        fontWeight = 700,
        letterSpacingSp = 0f.sp
    )
    val captionTinyStrong: AstroTextStyle = AstroTextStyle(
        fontSizeSp = 12.sp,
        lineHeightSp = 16.sp,
        fontWeight = 700,
        letterSpacingSp = (-0.3f).sp
    )
}
