// GENERATED by generators/android.mjs. Do not edit. Source: tokens/tokens.json
package com.astro.design.tokens

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object AstroDimens {
    val spacingXxsm: Dp = 2.dp
    val spacingXsm: Dp = 4.dp
    val spacingSm: Dp = 6.dp
    val spacingSmd: Dp = 8.dp
    val spacingMd: Dp = 10.dp
    val spacingMlg: Dp = 12.dp
    val spacingLg: Dp = 16.dp
    val spacingXlg: Dp = 18.dp
    val spacingXl: Dp = 20.dp
    val spacing2xl: Dp = 24.dp
    val spacing3xl: Dp = 32.dp
    val spacing4xl: Dp = 36.dp
    val spacing5xl: Dp = 40.dp
    val spacing6xl: Dp = 42.dp
    val spacing7xl: Dp = 44.dp
    val spacing8xl: Dp = 48.dp
    val spacing9xl: Dp = 56.dp
    val spacing10xl: Dp = 64.dp
    val spacing11xl: Dp = 72.dp
    val spacing12xl: Dp = 80.dp
    val spacing13xl: Dp = 88.dp
    val spacing14xl: Dp = 128.dp
    val radiusXxsm: Dp = 2.dp
    val radiusXsm: Dp = 4.dp
    val radiusXsmx: Dp = 6.dp
    val radiusSm: Dp = 8.dp
    val radiusMd: Dp = 12.dp
    val radiusLg: Dp = 16.dp
    val radiusXl: Dp = 999.dp
}
