// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).

import CoreGraphics

/// Astro design system spacing tokens, in points.
public enum AstroSpacing {
    /// space.xxsm (2px)
    public static let spacingXxsm: CGFloat = 2
    /// space.xsm (4px)
    public static let spacingXsm: CGFloat = 4
    /// space.sm (6px)
    public static let spacingSm: CGFloat = 6
    /// space.smd (8px)
    public static let spacingSmd: CGFloat = 8
    /// space.md (10px)
    public static let spacingMd: CGFloat = 10
    /// space.mlg (12px)
    public static let spacingMlg: CGFloat = 12
    /// space.lg (16px)
    public static let spacingLg: CGFloat = 16
    /// space.xlg (18px)
    public static let spacingXlg: CGFloat = 18
    /// space.xl (20px)
    public static let spacingXl: CGFloat = 20
    /// space.2xl (24px)
    public static let spacing2xl: CGFloat = 24
    /// space.3xl (32px)
    public static let spacing3xl: CGFloat = 32
    /// space.4xl (36px)
    public static let spacing4xl: CGFloat = 36
    /// space.5xl (40px)
    public static let spacing5xl: CGFloat = 40
    /// space.6xl (42px)
    public static let spacing6xl: CGFloat = 42
    /// space.7xl (44px)
    public static let spacing7xl: CGFloat = 44
    /// space.8xl (48px)
    public static let spacing8xl: CGFloat = 48
    /// space.9xl (56px)
    public static let spacing9xl: CGFloat = 56
    /// space.10xl (64px)
    public static let spacing10xl: CGFloat = 64
    /// space.11xl (72px)
    public static let spacing11xl: CGFloat = 72
    /// space.12xl (80px)
    public static let spacing12xl: CGFloat = 80
    /// space.13xl (88px)
    public static let spacing13xl: CGFloat = 88
    /// space.14xl (128px)
    public static let spacing14xl: CGFloat = 128
}
