// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).

import SwiftUI

/// Astro design system color tokens.
///
/// All 264 tokens live in this single flat namespace because the
/// canonical Android names are already flat and globally unique.
/// Primitive palettes (galaxy, nebula, neutral, sys and qd families)
/// come first, followed by semantic groups (buttons, backgrounds, text,
/// icons, strokes). Semantic aliases are resolved to hex values at
/// generation time, so every constant here is a concrete color.
public enum AstroColor {

    // MARK: galaxy

    public static let primaryGalaxy0 = Color(astroHex: 0xF3F6FA) // color.galaxy.0
    public static let primaryGalaxy1 = Color(astroHex: 0xE9F1FC) // color.galaxy.1
    public static let primaryGalaxy2 = Color(astroHex: 0xD3E2FA) // color.galaxy.2
    public static let primaryGalaxy3 = Color(astroHex: 0xBDD4F7) // color.galaxy.3
    public static let primaryGalaxy4 = Color(astroHex: 0xA7C5F5) // color.galaxy.4
    public static let primaryGalaxy5 = Color(astroHex: 0x92B7F2) // color.galaxy.5
    public static let primaryGalaxy6 = Color(astroHex: 0x7CA8EF) // color.galaxy.6
    public static let primaryGalaxy7 = Color(astroHex: 0x669AED) // color.galaxy.7
    public static let primaryGalaxy8 = Color(astroHex: 0x246EE5) // color.galaxy.8
    public static let primaryGalaxy9 = Color(astroHex: 0x2063CE) // color.galaxy.9
    public static let primaryGalaxy10 = Color(astroHex: 0x1D58B7) // color.galaxy.10
    public static let primaryGalaxy11 = Color(astroHex: 0x194DA0) // color.galaxy.11
    public static let primaryGalaxy12 = Color(astroHex: 0x164289) // color.galaxy.12
    public static let primaryGalaxy13 = Color(astroHex: 0x123773) // color.galaxy.13
    public static let primaryGalaxy14 = Color(astroHex: 0x0E2C5C) // color.galaxy.14
    public static let primaryGalaxy15 = Color(astroHex: 0x0B2145) // color.galaxy.15

    // MARK: nebula

    public static let secondaryNebula1 = Color(astroHex: 0xFFE9E6) // color.nebula.1
    public static let secondaryNebula2 = Color(astroHex: 0xFFD2CC) // color.nebula.2
    public static let secondaryNebula3 = Color(astroHex: 0xFFBCB3) // color.nebula.3
    public static let secondaryNebula4 = Color(astroHex: 0xFFA599) // color.nebula.4
    public static let secondaryNebula5 = Color(astroHex: 0xFF8F80) // color.nebula.5
    public static let secondaryNebula6 = Color(astroHex: 0xFF7866) // color.nebula.6
    public static let secondaryNebula7 = Color(astroHex: 0xFF624D) // color.nebula.7
    public static let secondaryNebula8 = Color(astroHex: 0xFF1E00) // color.nebula.8
    public static let secondaryNebula9 = Color(astroHex: 0xE61B00) // color.nebula.9
    public static let secondaryNebula10 = Color(astroHex: 0xCC1800) // color.nebula.10
    public static let secondaryNebula11 = Color(astroHex: 0xB31500) // color.nebula.11
    public static let secondaryNebula12 = Color(astroHex: 0x991200) // color.nebula.12
    public static let secondaryNebula13 = Color(astroHex: 0x800F00) // color.nebula.13
    public static let secondaryNebula14 = Color(astroHex: 0x660C00) // color.nebula.14
    public static let secondaryNebula15 = Color(astroHex: 0x4C0900) // color.nebula.15

    // MARK: neutral

    public static let neutralNeutral1 = Color(astroHex: 0xFFFFFF) // color.neutral.1
    public static let neutralNeutral2 = Color(astroHex: 0xE9E9E9) // color.neutral.2
    public static let neutralNeutral3 = Color(astroHex: 0xD3D3D3) // color.neutral.3
    public static let neutralNeutral4 = Color(astroHex: 0xBCBCBC) // color.neutral.4
    public static let neutralNeutral5 = Color(astroHex: 0xA6A6A6) // color.neutral.5
    public static let neutralNeutral6 = Color(astroHex: 0x909090) // color.neutral.6
    public static let neutralNeutral7 = Color(astroHex: 0x7A7A7A) // color.neutral.7
    public static let neutralNeutral8 = Color(astroHex: 0x646464) // color.neutral.8
    public static let neutralNeutral9 = Color(astroHex: 0x373737) // color.neutral.9
    public static let neutralNeutral10 = Color(astroHex: 0x212121) // color.neutral.10
    public static let neutralNeutral11 = Color(astroHex: 0x141414) // color.neutral.11
    public static let neutralNeutral12 = Color(astroHex: 0x070707) // color.neutral.12
    public static let neutralSpecial = Color(astroHex: 0xFAFAFA) // color.neutral.special

    // MARK: sysGreen

    public static let sysGreenGr1 = Color(astroHex: 0xE6F7EF) // color.sysGreen.1
    public static let sysGreenGr2 = Color(astroHex: 0xCCEEDE) // color.sysGreen.2
    public static let sysGreenGr3 = Color(astroHex: 0xB3E6CE) // color.sysGreen.3
    public static let sysGreenGr4 = Color(astroHex: 0x99DDBD) // color.sysGreen.4
    public static let sysGreenGr5 = Color(astroHex: 0x80D5AD) // color.sysGreen.5
    public static let sysGreenGr6 = Color(astroHex: 0x66CC9D) // color.sysGreen.6
    public static let sysGreenGr7 = Color(astroHex: 0x4DC48C) // color.sysGreen.7
    public static let sysGreenGr8 = Color(astroHex: 0x00AA5B) // color.sysGreen.8
    public static let sysGreenGr9 = Color(astroHex: 0x009952) // color.sysGreen.9
    public static let sysGreenGr10 = Color(astroHex: 0x008849) // color.sysGreen.10
    public static let sysGreenGr11 = Color(astroHex: 0x007740) // color.sysGreen.11
    public static let sysGreenGr12 = Color(astroHex: 0x006637) // color.sysGreen.12
    public static let sysGreenGr13 = Color(astroHex: 0x00552E) // color.sysGreen.13
    public static let sysGreenGr14 = Color(astroHex: 0x004424) // color.sysGreen.14
    public static let sysGreenGr15 = Color(astroHex: 0x00331B) // color.sysGreen.15

    // MARK: sysOrange

    public static let sysOrangeOr1 = Color(astroHex: 0xFFF3E6) // color.sysOrange.1
    public static let sysOrangeOr2 = Color(astroHex: 0xFFE7CC) // color.sysOrange.2
    public static let sysOrangeOr3 = Color(astroHex: 0xFFDAB3) // color.sysOrange.3
    public static let sysOrangeOr4 = Color(astroHex: 0xFFCE99) // color.sysOrange.4
    public static let sysOrangeOr5 = Color(astroHex: 0xFFC280) // color.sysOrange.5
    public static let sysOrangeOr6 = Color(astroHex: 0xFFB666) // color.sysOrange.6
    public static let sysOrangeOr7 = Color(astroHex: 0xFFAA4D) // color.sysOrange.7
    public static let sysOrangeOr8 = Color(astroHex: 0xFF8500) // color.sysOrange.8
    public static let sysOrangeOr9 = Color(astroHex: 0xE67800) // color.sysOrange.9
    public static let sysOrangeOr10 = Color(astroHex: 0xCC6A00) // color.sysOrange.10
    public static let sysOrangeOr11 = Color(astroHex: 0xB35D00) // color.sysOrange.11
    public static let sysOrangeOr12 = Color(astroHex: 0x995000) // color.sysOrange.12
    public static let sysOrangeOr13 = Color(astroHex: 0x804300) // color.sysOrange.13
    public static let sysOrangeOr14 = Color(astroHex: 0x663500) // color.sysOrange.14
    public static let sysOrangeOr15 = Color(astroHex: 0x4C2800) // color.sysOrange.15

    // MARK: sysRed

    public static let sysRedRd1 = Color(astroHex: 0xFEEDEF) // color.sysRed.1
    public static let sysRedRd2 = Color(astroHex: 0xFEDBE0) // color.sysRed.2
    public static let sysRedRd3 = Color(astroHex: 0xFDCAD0) // color.sysRed.3
    public static let sysRedRd4 = Color(astroHex: 0xFDB8C1) // color.sysRed.4
    public static let sysRedRd5 = Color(astroHex: 0xFCA6B1) // color.sysRed.5
    public static let sysRedRd6 = Color(astroHex: 0xFB94A1) // color.sysRed.6
    public static let sysRedRd7 = Color(astroHex: 0xFB8292) // color.sysRed.7
    public static let sysRedRd8 = Color(astroHex: 0xF94D63) // color.sysRed.8
    public static let sysRedRd9 = Color(astroHex: 0xE04559) // color.sysRed.9
    public static let sysRedRd10 = Color(astroHex: 0xC73E4F) // color.sysRed.10
    public static let sysRedRed11 = Color(astroHex: 0xAE3645) // color.sysRed.11
    public static let sysRedRed12 = Color(astroHex: 0x952E3B) // color.sysRed.12
    public static let sysRedRed13 = Color(astroHex: 0x7D2732) // color.sysRed.13
    public static let sysRedRed14 = Color(astroHex: 0x641F28) // color.sysRed.14
    public static let sysRedRed15 = Color(astroHex: 0x4B171E) // color.sysRed.15

    // MARK: qdYellow

    public static let qdYellowYl1 = Color(astroHex: 0xFFF8E7) // color.qdYellow.1
    public static let qdYellowYl2 = Color(astroHex: 0xFFF1CE) // color.qdYellow.2
    public static let qdYellowYl3 = Color(astroHex: 0xFFEBB6) // color.qdYellow.3
    public static let qdYellowYl4 = Color(astroHex: 0xFFE49E) // color.qdYellow.4
    public static let qdYellowYl5 = Color(astroHex: 0xFFDD86) // color.qdYellow.5
    public static let qdYellowYl6 = Color(astroHex: 0xFFD66D) // color.qdYellow.6
    public static let qdYellowYl7 = Color(astroHex: 0xFFCF55) // color.qdYellow.7
    public static let qdYellowYl8 = Color(astroHex: 0xFFBB0C) // color.qdYellow.8
    public static let qdYellowYl9 = Color(astroHex: 0xE6A80B) // color.qdYellow.9
    public static let qdYellowYl10 = Color(astroHex: 0xCC960A) // color.qdYellow.10
    public static let qdYellowYl11 = Color(astroHex: 0xB38308) // color.qdYellow.11
    public static let qdYellowYl12 = Color(astroHex: 0x997007) // color.qdYellow.12
    public static let qdYellowYl13 = Color(astroHex: 0x805E06) // color.qdYellow.13
    public static let qdYellowYl14 = Color(astroHex: 0x664B05) // color.qdYellow.14
    public static let qdYellowYl15 = Color(astroHex: 0x4C3804) // color.qdYellow.15

    // MARK: qdCyan

    public static let qdCyanCy1 = Color(astroHex: 0xEEFBFD) // color.qdCyan.1
    public static let qdCyanCy2 = Color(astroHex: 0xDEF7FA) // color.qdCyan.2
    public static let qdCyanCy3 = Color(astroHex: 0xCDF4F8) // color.qdCyan.3
    public static let qdCyanCy4 = Color(astroHex: 0xBCF0F5) // color.qdCyan.4
    public static let qdCyanCy5 = Color(astroHex: 0xACECF3) // color.qdCyan.5
    public static let qdCyanCy6 = Color(astroHex: 0x9BE8F0) // color.qdCyan.6
    public static let qdCyanCy7 = Color(astroHex: 0x8AE4EE) // color.qdCyan.7
    public static let qdCyanCy8 = Color(astroHex: 0x58D9E6) // color.qdCyan.8
    public static let qdCyanCy9 = Color(astroHex: 0x4FC3CF) // color.qdCyan.9
    public static let qdCyanCy10 = Color(astroHex: 0x46AEB8) // color.qdCyan.10
    public static let qdCyanCy11 = Color(astroHex: 0x3E98A1) // color.qdCyan.11
    public static let qdCyanCy12 = Color(astroHex: 0x35828A) // color.qdCyan.12
    public static let qdCyanCy13 = Color(astroHex: 0x2C6D73) // color.qdCyan.13
    public static let qdCyanCy14 = Color(astroHex: 0x23575C) // color.qdCyan.14
    public static let qdCyanCy15 = Color(astroHex: 0x1A4145) // color.qdCyan.15

    // MARK: qdPurple

    public static let qdPurplePr1 = Color(astroHex: 0xF0EDF8) // color.qdPurple.1
    public static let qdPurplePr2 = Color(astroHex: 0xE1DAF1) // color.qdPurple.2
    public static let qdPurplePr3 = Color(astroHex: 0xD2C8EB) // color.qdPurple.3
    public static let qdPurplePr4 = Color(astroHex: 0xC3B5E4) // color.qdPurple.4
    public static let qdPurplePr5 = Color(astroHex: 0xB4A3DD) // color.qdPurple.5
    public static let qdPurplePr6 = Color(astroHex: 0xA491D6) // color.qdPurple.6
    public static let qdPurplePr7 = Color(astroHex: 0x957ECF) // color.qdPurple.7
    public static let qdPurplePr8 = Color(astroHex: 0x6847BB) // color.qdPurple.8
    public static let qdPurplePr9 = Color(astroHex: 0x5E40A8) // color.qdPurple.9
    public static let qdPurplePr10 = Color(astroHex: 0x533996) // color.qdPurple.10
    public static let qdPurplePr11 = Color(astroHex: 0x493283) // color.qdPurple.11
    public static let qdPurplePr12 = Color(astroHex: 0x3E2B70) // color.qdPurple.12
    public static let qdPurplePr13 = Color(astroHex: 0x34245E) // color.qdPurple.13
    public static let qdPurplePr14 = Color(astroHex: 0x2A1C4B) // color.qdPurple.14
    public static let qdPurplePr15 = Color(astroHex: 0x1F1538) // color.qdPurple.15

    // MARK: qdMagenta

    public static let qdMagentaMg1 = Color(astroHex: 0xF6E6FC) // color.qdMagenta.1
    public static let qdMagentaMg2 = Color(astroHex: 0xEDCCF9) // color.qdMagenta.2
    public static let qdMagentaMg3 = Color(astroHex: 0xE4B3F6) // color.qdMagenta.3
    public static let qdMagentaMg4 = Color(astroHex: 0xDB99F3) // color.qdMagenta.4
    public static let qdMagentaMg5 = Color(astroHex: 0xD280F0) // color.qdMagenta.5
    public static let qdMagentaMg6 = Color(astroHex: 0xC966EC) // color.qdMagenta.6
    public static let qdMagentaMg7 = Color(astroHex: 0xC04DE9) // color.qdMagenta.7
    public static let qdMagentaMg8 = Color(astroHex: 0xA500E0) // color.qdMagenta.8
    public static let qdMagentaMg9 = Color(astroHex: 0x9500CA) // color.qdMagenta.9
    public static let qdMagentaMg10 = Color(astroHex: 0x8400B3) // color.qdMagenta.10
    public static let qdMagentaMg11 = Color(astroHex: 0x73009D) // color.qdMagenta.11
    public static let qdMagentaMg12 = Color(astroHex: 0x630086) // color.qdMagenta.12
    public static let qdMagentaMg13 = Color(astroHex: 0x630086) // color.qdMagenta.13
    public static let qdMagentaMg14 = Color(astroHex: 0x42005A) // color.qdMagenta.14
    public static let qdMagentaMg15 = Color(astroHex: 0x310043) // color.qdMagenta.15

    // MARK: btnPrimary

    public static let btnPrimaryDisable = Color(astroHex: 0xE9E9E9) // color.btnPrimary.disable -> {color.neutral.2}
    public static let btnPrimaryDefault = Color(astroHex: 0x246EE5) // color.btnPrimary.default -> {color.galaxy.8}
    public static let btnPrimaryHover = Color(astroHex: 0x194DA0) // color.btnPrimary.hover -> {color.galaxy.11}
    public static let btnPrimarySelected = Color(astroHex: 0x123773) // color.btnPrimary.selected -> {color.galaxy.13}
    public static let btnPrimaryOutline = Color(astroHex: 0x246EE5) // color.btnPrimary.outline -> {color.galaxy.8}
    public static let btnPrimaryOutlineHover = Color(astroHex: 0xBDD4F7) // color.btnPrimary.outlineHover -> {color.galaxy.3}
    public static let btnPrimaryOutlineSelected = Color(astroHex: 0x92B7F2) // color.btnPrimary.outlineSelected -> {color.galaxy.5}
    public static let btnPrimaryOutlineDisable = Color(astroHex: 0xD3D3D3) // color.btnPrimary.outlineDisable -> {color.neutral.3}

    // MARK: btnSecondary

    public static let btnSecondaryDisable = Color(astroHex: 0xE9E9E9) // color.btnSecondary.disable -> {color.neutral.2}
    public static let btnSecondaryDefault = Color(astroHex: 0xFF1E00) // color.btnSecondary.default -> {color.nebula.8}
    public static let btnSecondaryHover = Color(astroHex: 0xB31500) // color.btnSecondary.hover -> {color.nebula.11}
    public static let btnSecondarySelected = Color(astroHex: 0x800F00) // color.btnSecondary.selected -> {color.nebula.13}
    public static let btnSecondaryOutline = Color(astroHex: 0xFF1E00) // color.btnSecondary.outline -> {color.nebula.8}
    public static let btnSecondaryOutlineHover = Color(astroHex: 0xFFBCB3) // color.btnSecondary.outlineHover -> {color.nebula.3}
    public static let btnSecondaryOutlineSelected = Color(astroHex: 0xFF8F80) // color.btnSecondary.outlineSelected -> {color.nebula.5}
    public static let btnSecondaryOutlineDisable = Color(astroHex: 0xD3D3D3) // color.btnSecondary.outlineDisable -> {color.neutral.3}

    // MARK: btnNeutral

    public static let btnNeutralDefault = Color(astroHex: 0xE9E9E9) // color.btnNeutral.default -> {color.neutral.2}
    public static let btnNeutralHover = Color(astroHex: 0xD3D3D3) // color.btnNeutral.hover -> {color.neutral.3}
    public static let btnNeutralSelected = Color(astroHex: 0xBCBCBC) // color.btnNeutral.selected -> {color.neutral.4}
    public static let btnNeutralDisable = Color(astroHex: 0xBCBCBC) // color.btnNeutral.disable -> {color.neutral.4}
    public static let btnNeutralOutline = Color(astroHex: 0xD3D3D3) // color.btnNeutral.outline -> {color.neutral.3}
    public static let btnNeutralOutlineHover = Color(astroHex: 0xE9E9E9) // color.btnNeutral.outlineHover -> {color.neutral.2}
    public static let btnNeutralOutlineSelected = Color(astroHex: 0xD3D3D3) // color.btnNeutral.outlineSelected -> {color.neutral.3}
    public static let btnNeutralOutlineDisable = Color(astroHex: 0xD3D3D3) // color.btnNeutral.outlineDisable -> {color.neutral.3}

    // MARK: bgColor

    public static let bgColorLight = Color(astroHex: 0xFFFFFF) // color.bgColor.light -> {color.neutral.1}
    public static let bgColorDisable = Color(astroHex: 0xFAFAFA) // color.bgColor.disable -> {color.neutral.special}
    public static let bgColorDisableD = Color(astroHex: 0xE9E9E9) // color.bgColor.disableD -> {color.neutral.2}
    public static let bgColorDark = Color(astroHex: 0x212121) // color.bgColor.dark -> {color.neutral.10}
    public static let bgColorDarker = Color(astroHex: 0x373737) // color.bgColor.darker -> {color.neutral.9}
    public static let bgColorLightPrimary = Color(astroHex: 0xE9F1FC) // color.bgColor.lightPrimary -> {color.galaxy.1}
    public static let bgColorSLightPrimary = Color(astroHex: 0xA7C5F5) // color.bgColor.sLightPrimary -> {color.galaxy.4}
    public static let bgColorPrimary = Color(astroHex: 0x246EE5) // color.bgColor.primary -> {color.galaxy.8}
    public static let bgColorPrimaryDark = Color(astroHex: 0x0B2145) // color.bgColor.primaryDark -> {color.galaxy.15}
    public static let bgColorSecondary = Color(astroHex: 0xE61B00) // color.bgColor.secondary -> {color.nebula.9}
    public static let bgColorLightSecondary = Color(astroHex: 0xFFE9E6) // color.bgColor.lightSecondary -> {color.nebula.1}
    public static let bgColorLightGreen = Color(astroHex: 0xE6F7EF) // color.bgColor.lightGreen -> {color.sysGreen.1}
    public static let bgColorLightRed = Color(astroHex: 0xFEEDEF) // color.bgColor.lightRed -> {color.sysRed.1}
    public static let bgColorLightOrange = Color(astroHex: 0xFFF3E6) // color.bgColor.lightOrange -> {color.sysOrange.1}
    public static let bgColorLightBlue = Color(astroHex: 0xE9F1FC) // color.bgColor.lightBlue -> {color.galaxy.1}
    public static let bgColorLightGrey = Color(astroHex: 0xE9E9E9) // color.bgColor.lightGrey -> {color.neutral.2}
    public static let bgColorLightYellow = Color(astroHex: 0xFFF8E7) // color.bgColor.lightYellow -> {color.qdYellow.1}
    public static let bgColorLightCyan = Color(astroHex: 0xEEFBFD) // color.bgColor.lightCyan -> {color.qdCyan.1}
    public static let bgColorLightPurple = Color(astroHex: 0xF0EDF8) // color.bgColor.lightPurple -> {color.qdPurple.1}
    public static let bgColorLightMagenta = Color(astroHex: 0xF6E6FC) // color.bgColor.lightMagenta -> {color.qdMagenta.1}
    public static let bgColorGreen = Color(astroHex: 0x00AA5B) // color.bgColor.green -> {color.sysGreen.8}
    public static let bgColorGreenDark = Color(astroHex: 0x007740) // color.bgColor.greenDark -> {color.sysGreen.11}
    public static let bgColorRed = Color(astroHex: 0xF94D63) // color.bgColor.red -> {color.sysRed.8}
    public static let bgColorRedDark = Color(astroHex: 0xAE3645) // color.bgColor.redDark -> {color.sysRed.11}
    public static let bgColorOrange = Color(astroHex: 0xFF8500) // color.bgColor.orange -> {color.sysOrange.8}
    public static let bgColorOrangeDark = Color(astroHex: 0xB35D00) // color.bgColor.orangeDark -> {color.sysOrange.11}
    public static let bgColorBlue = Color(astroHex: 0x2063CE) // color.bgColor.blue -> {color.galaxy.9}
    public static let bgColorBlueDark = Color(astroHex: 0x194DA0) // color.bgColor.blueDark -> {color.galaxy.11}
    public static let bgColorGrey = Color(astroHex: 0x909090) // color.bgColor.grey -> {color.neutral.6}
    public static let bgColorSLightGrey = Color(astroHex: 0xBCBCBC) // color.bgColor.sLightGrey -> {color.neutral.4}
    public static let bgColorGreyDark = Color(astroHex: 0x7A7A7A) // color.bgColor.greyDark -> {color.neutral.7}
    public static let bgColorYellow = Color(astroHex: 0xFFBB0C) // color.bgColor.yellow -> {color.qdYellow.8}
    public static let bgColorYellowDark = Color(astroHex: 0xB38308) // color.bgColor.yellowDark -> {color.qdYellow.11}
    public static let bgColorCyan = Color(astroHex: 0x58D9E6) // color.bgColor.cyan -> {color.qdCyan.8}
    public static let bgColorCyanDark = Color(astroHex: 0x3E98A1) // color.bgColor.cyanDark -> {color.qdCyan.11}
    public static let bgColorPurple = Color(astroHex: 0x6847BB) // color.bgColor.purple -> {color.qdPurple.8}
    public static let bgColorPurpleDark = Color(astroHex: 0x493283) // color.bgColor.purpleDark -> {color.qdPurple.11}
    public static let bgColorMagenta = Color(astroHex: 0xA500E0) // color.bgColor.magenta -> {color.qdMagenta.8}
    public static let bgColorMagentaBlack = Color(astroHex: 0x73009D) // color.bgColor.magentaBlack -> {color.qdMagenta.11}
    public static let bgColorVlightPrimary = Color(astroHex: 0xF3F6FA) // color.bgColor.vlightPrimary -> {color.galaxy.0}

    // MARK: textColor

    public static let textColorPrimaryDark = Color(astroHex: 0x212121) // color.textColor.primaryDark -> {color.neutral.10}
    public static let textColorSecondaryDark = Color(astroHex: 0x646464) // color.textColor.secondaryDark -> {color.neutral.8}
    public static let textColorPrimaryLight = Color(astroHex: 0xFFFFFF) // color.textColor.primaryLight -> {color.neutral.1}
    public static let textColorSecondaryLight = Color(astroHex: 0xD3D3D3) // color.textColor.secondaryLight -> {color.neutral.3}
    public static let textColorPlaceholder = Color(astroHex: 0xA6A6A6) // color.textColor.placeholder -> {color.neutral.5}
    public static let textColorDisable = Color(astroHex: 0xA6A6A6) // color.textColor.disable -> {color.neutral.5}
    public static let textColorBtnDisable = Color(astroHex: 0xBDD4F7) // color.textColor.btnDisable -> {color.galaxy.3}
    public static let textColorLink = Color(astroHex: 0x246EE5) // color.textColor.link -> {color.galaxy.8}
    public static let textColorLinkHover = Color(astroHex: 0x194DA0) // color.textColor.linkHover -> {color.galaxy.11}
    public static let textColorLinkSelected = Color(astroHex: 0x123773) // color.textColor.linkSelected -> {color.galaxy.13}
    public static let textColorError = Color(astroHex: 0xF94D63) // color.textColor.error -> {color.sysRed.8}
    public static let textColorWarning = Color(astroHex: 0xE67800) // color.textColor.warning -> {color.sysOrange.9}
    public static let textColorSucess = Color(astroHex: 0x00AA5B) // color.textColor.sucess -> {color.sysGreen.8}
    public static let textColorLinkSecondary = Color(astroHex: 0xE61B00) // color.textColor.linkSecondary -> {color.nebula.9}
    public static let textColorYellow = Color(astroHex: 0xFFBB0C) // color.textColor.yellow -> {color.qdYellow.8}
    public static let textColorCyan = Color(astroHex: 0x4FC3CF) // color.textColor.cyan -> {color.qdCyan.9}
    public static let textColorPurple = Color(astroHex: 0x6847BB) // color.textColor.purple -> {color.qdPurple.8}
    public static let textColorMagenta = Color(astroHex: 0xA500E0) // color.textColor.magenta -> {color.qdMagenta.8}

    // MARK: iconColor

    public static let iconColorDefault = Color(astroHex: 0x646464) // color.iconColor.default -> {color.neutral.8}
    public static let iconColorDefaultAlt = Color(astroHex: 0x909090) // color.iconColor.defaultAlt -> {color.neutral.6}
    public static let iconColorDark = Color(astroHex: 0x212121) // color.iconColor.dark -> {color.neutral.10}
    public static let iconColorPlaceholder = Color(astroHex: 0xE9E9E9) // color.iconColor.placeholder -> {color.neutral.2}
    public static let iconColorDisable = Color(astroHex: 0xA6A6A6) // color.iconColor.disable -> {color.neutral.5}
    public static let iconColorLight = Color(astroHex: 0xFFFFFF) // color.iconColor.light -> {color.neutral.1}
    public static let iconColorRed = Color(astroHex: 0xF94D63) // color.iconColor.red -> {color.sysRed.8}
    public static let iconColorGreen = Color(astroHex: 0x00AA5B) // color.iconColor.green -> {color.sysGreen.8}
    public static let iconColorOrange = Color(astroHex: 0xFF8500) // color.iconColor.orange -> {color.sysOrange.8}
    public static let iconColorPrimary = Color(astroHex: 0x246EE5) // color.iconColor.primary -> {color.galaxy.8}
    public static let iconColorPrimaryHover = Color(astroHex: 0x194DA0) // color.iconColor.primaryHover -> {color.galaxy.11}
    public static let iconColorPrimarySelected = Color(astroHex: 0x123773) // color.iconColor.primarySelected -> {color.galaxy.13}
    public static let iconColorYellow = Color(astroHex: 0xFFBB0C) // color.iconColor.yellow -> {color.qdYellow.8}
    public static let iconColorCyan = Color(astroHex: 0x58D9E6) // color.iconColor.cyan -> {color.qdCyan.8}
    public static let iconColorPurple = Color(astroHex: 0x6847BB) // color.iconColor.purple -> {color.qdPurple.8}
    public static let iconColorMagenta = Color(astroHex: 0xA500E0) // color.iconColor.magenta -> {color.qdMagenta.8}
    public static let iconColorSecondary = Color(astroHex: 0xFF1E00) // color.iconColor.secondary -> {color.nebula.8}

    // MARK: strokeColor

    public static let strokeColorDefault = Color(astroHex: 0xD3D3D3) // color.strokeColor.default -> {color.neutral.3}
    public static let strokeColorSubtle = Color(astroHex: 0xE9E9E9) // color.strokeColor.subtle -> {color.neutral.2}
    public static let strokeColorDisable = Color(astroHex: 0xD3D3D3) // color.strokeColor.disable -> {color.neutral.3}
    public static let strokeColorLight = Color(astroHex: 0xFFFFFF) // color.strokeColor.light -> {color.neutral.1}
    public static let strokeColorActive = Color(astroHex: 0x246EE5) // color.strokeColor.active -> {color.galaxy.8}
    public static let strokeColorError = Color(astroHex: 0xFF1E00) // color.strokeColor.error -> {color.nebula.8}
    public static let strokeColorSucess = Color(astroHex: 0x00AA5B) // color.strokeColor.sucess -> {color.sysGreen.8}
    public static let strokeColorFilled = Color(astroHex: 0x646464) // color.strokeColor.filled -> {color.neutral.8}
    public static let strokeColorWarning = Color(astroHex: 0xFF8500) // color.strokeColor.warning -> {color.sysOrange.8}
    public static let strokeColorDark = Color(astroHex: 0x373737) // color.strokeColor.dark -> {color.neutral.9}

    // MARK: desktopMultiSelection

    public static let desktopMutliSelectionText = Color(astroHex: 0xA6A6A6) // color.desktopMultiSelection.text -> {color.neutral.5}
    public static let desktopMutliSelectionBgColor = Color(astroHex: 0xE9E9E9) // color.desktopMultiSelection.bgColor -> {color.neutral.2}
    public static let desktopMutliSelectionIcon = Color(astroHex: 0xA6A6A6) // color.desktopMultiSelection.icon -> {color.neutral.5}
    public static let desktopMutliSelectionStroke = Color(astroHex: 0xD3D3D3) // color.desktopMultiSelection.stroke -> {color.neutral.3}

    // MARK: tagging

    public static let taggingText = Color(astroHex: 0x646464) // color.tagging.text -> {color.neutral.8}
    public static let taggingBgColor = Color(astroHex: 0xE9E9E9) // color.tagging.bgColor -> {color.neutral.2}
}
