// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).

import CoreGraphics

/// Astro design system corner radius tokens, in points.
public enum AstroRadius {
    /// radius.xxsm (2px)
    public static let radiusXxsm: CGFloat = 2
    /// radius.xsm (4px)
    public static let radiusXsm: CGFloat = 4
    /// radius.xsmx (6px)
    public static let radiusXsmx: CGFloat = 6
    /// radius.sm (8px)
    public static let radiusSm: CGFloat = 8
    /// radius.md (12px)
    public static let radiusMd: CGFloat = 12
    /// radius.lg (16px)
    public static let radiusLg: CGFloat = 16
    /// radius.xl (999px)
    public static let radiusXl: CGFloat = 999
}
