// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).

import SwiftUI

/// A resolved Astro text style.
///
/// Sizes are in points. `letterSpacing` uses the Android sp value when
/// the token defines one (androidLetterSpacingSp) and 0 otherwise, so
/// it can be passed straight to `.tracking(_:)`.
public struct AstroTextStyle {
    public let fontSize: CGFloat
    public let lineHeight: CGFloat
    public let weight: Font.Weight
    public let letterSpacing: CGFloat

    public init(fontSize: CGFloat, lineHeight: CGFloat, weight: Font.Weight, letterSpacing: CGFloat) {
        self.fontSize = fontSize
        self.lineHeight = lineHeight
        self.weight = weight
        self.letterSpacing = letterSpacing
    }
}

/// Astro design system text style tokens.
public enum AstroTypography {

    // MARK: display

    /// text.display.huge
    public static let displayHuge = AstroTextStyle(fontSize: 42, lineHeight: 48, weight: .heavy, letterSpacing: -0.3)
    /// text.display.large
    public static let displayLarge = AstroTextStyle(fontSize: 36, lineHeight: 42, weight: .heavy, letterSpacing: -0.3)
    /// text.display.small
    public static let displaySmall = AstroTextStyle(fontSize: 30, lineHeight: 36, weight: .heavy, letterSpacing: -0.3)
    /// text.display.tiny
    public static let displayTiny = AstroTextStyle(fontSize: 24, lineHeight: 30, weight: .heavy, letterSpacing: -0.3)

    // MARK: headline

    /// text.headline.large
    public static let headlineLarge = AstroTextStyle(fontSize: 20, lineHeight: 28, weight: .heavy, letterSpacing: -0.2)
    /// text.headline.default
    public static let headlineDefault = AstroTextStyle(fontSize: 18, lineHeight: 26, weight: .heavy, letterSpacing: -0.2)
    /// text.headline.small
    public static let headlineSmall = AstroTextStyle(fontSize: 16, lineHeight: 24, weight: .heavy, letterSpacing: -0.2)
    /// text.headline.tiny
    public static let headlineTiny = AstroTextStyle(fontSize: 14, lineHeight: 20, weight: .bold, letterSpacing: -0.1)
    /// text.headline.superTiny
    public static let headlineSuperTiny = AstroTextStyle(fontSize: 12, lineHeight: 16, weight: .bold, letterSpacing: -0.3)

    // MARK: body

    /// text.body.large
    public static let bodyLarge = AstroTextStyle(fontSize: 18, lineHeight: 24, weight: .semibold, letterSpacing: -0.2)
    /// text.body.largeStrong
    public static let bodyLargeStrong = AstroTextStyle(fontSize: 18, lineHeight: 24, weight: .bold, letterSpacing: -0.2)
    /// text.body.default
    public static let bodyDefault = AstroTextStyle(fontSize: 16, lineHeight: 22, weight: .semibold, letterSpacing: 0)
    /// text.body.defaultStrong
    public static let bodyDefaultStrong = AstroTextStyle(fontSize: 16, lineHeight: 22, weight: .bold, letterSpacing: 0)
    /// text.body.small
    public static let bodySmall = AstroTextStyle(fontSize: 14, lineHeight: 20, weight: .semibold, letterSpacing: -0.1)
    /// text.body.smallStrong
    public static let bodySmallStrong = AstroTextStyle(fontSize: 14, lineHeight: 20, weight: .bold, letterSpacing: -0.1)
    /// text.body.tiny
    public static let bodyTiny = AstroTextStyle(fontSize: 12, lineHeight: 16, weight: .semibold, letterSpacing: -0.3)
    /// text.body.tinyStrong
    public static let bodyTinyStrong = AstroTextStyle(fontSize: 12, lineHeight: 16, weight: .bold, letterSpacing: -0.3)

    // MARK: paragraph

    /// text.paragraph.large
    public static let paragraphLarge = AstroTextStyle(fontSize: 18, lineHeight: 26, weight: .regular, letterSpacing: 0)
    /// text.paragraph.default
    public static let paragraphDefault = AstroTextStyle(fontSize: 16, lineHeight: 24, weight: .regular, letterSpacing: 0)
    /// text.paragraph.small
    public static let paragraphSmall = AstroTextStyle(fontSize: 14, lineHeight: 22, weight: .regular, letterSpacing: 0)
    /// text.paragraph.tiny
    public static let paragraphTiny = AstroTextStyle(fontSize: 12, lineHeight: 18, weight: .regular, letterSpacing: 0)

    // MARK: caption

    /// text.caption.default
    public static let captionDefault = AstroTextStyle(fontSize: 14, lineHeight: 20, weight: .regular, letterSpacing: 0)
    /// text.caption.small
    public static let captionSmall = AstroTextStyle(fontSize: 12, lineHeight: 16, weight: .regular, letterSpacing: 0)
    /// text.caption.tiny
    public static let captionTiny = AstroTextStyle(fontSize: 10, lineHeight: 12, weight: .regular, letterSpacing: 0)
    /// text.caption.tinyBold
    public static let captionTinyBold = AstroTextStyle(fontSize: 10, lineHeight: 12, weight: .bold, letterSpacing: 0)
    /// text.caption.tinyStrong
    public static let captionTinyStrong = AstroTextStyle(fontSize: 12, lineHeight: 16, weight: .bold, letterSpacing: -0.3)
}
