// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).

import SwiftUI

extension Color {
    /// Creates an opaque sRGB color from a packed 24 bit 0xRRGGBB value.
    init(astroHex hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255.0,
            green: Double((hex >> 8) & 0xFF) / 255.0,
            blue: Double(hex & 0xFF) / 255.0,
            opacity: 1.0
        )
    }
}
