#!/usr/bin/env node
// Android token generator. Run from repo root: node generators/android.mjs
// Reads tokens/tokens.json (values) and tokens/platform-names.json (names)
// and emits Kotlin sources for the :tokens Android library module.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(repoRoot, "tokens", "tokens.json"), "utf8"));
const platformNames = JSON.parse(readFileSync(join(repoRoot, "tokens", "platform-names.json"), "utf8"));

const outDir = join(
  repoRoot,
  "packages", "android", "tokens", "src", "main", "kotlin",
  "com", "astro", "design", "tokens"
);
mkdirSync(outDir, { recursive: true });

const HEADER = "// GENERATED by generators/android.mjs. Do not edit. Source: tokens/tokens.json\n";

// Look up a token node by dotted path, e.g. "color.galaxy.8".
function getNode(path) {
  let node = tokens;
  for (const part of path.split(".")) {
    if (node == null || typeof node !== "object") return undefined;
    node = node[part];
  }
  return node;
}

// Resolve a token value, following {alias.path} references.
function resolveValue(value, seen = new Set()) {
  if (typeof value === "string") {
    const match = value.match(/^\{([^}]+)\}$/);
    if (match) {
      const refPath = match[1];
      if (seen.has(refPath)) throw new Error(`Circular alias: ${refPath}`);
      seen.add(refPath);
      const node = getNode(refPath);
      if (node === undefined || node.$value === undefined) {
        throw new Error(`Unresolvable alias: {${refPath}}`);
      }
      return resolveValue(node.$value, seen);
    }
  }
  return value;
}

function pxToNumber(value, context) {
  const match = String(value).match(/^(-?\d+(?:\.\d+)?)px$/);
  if (!match) throw new Error(`Expected px dimension for ${context}, got: ${value}`);
  return Number(match[1]);
}

function hexToKotlinColor(value, context) {
  const match = String(value).match(/^#([0-9a-fA-F]{6})$/);
  if (!match) throw new Error(`Expected 6-digit hex color for ${context}, got: ${value}`);
  return `Color(0xFF${match[1].toUpperCase()})`;
}

// Format a number as a Kotlin float literal wrapped for .sp use.
function spLiteral(num) {
  const literal = Number.isInteger(num) ? `${num}f` : `${num}f`;
  return num < 0 ? `(${literal}).sp` : `${literal}.sp`;
}

// AstroColors.kt
const colorLines = [];
let colorCount = 0;
let colorSkipped = 0;
for (const [tokenPath, names] of Object.entries(platformNames.color)) {
  if (names.android == null) {
    colorSkipped++;
    continue;
  }
  const node = getNode(tokenPath);
  if (node === undefined || node.$value === undefined) {
    throw new Error(`Token not found in tokens.json: ${tokenPath}`);
  }
  const hex = resolveValue(node.$value);
  colorLines.push(`    val ${names.android}: Color = ${hexToKotlinColor(hex, tokenPath)}`);
  colorCount++;
}

const astroColors = `${HEADER}package com.astro.design.tokens

import androidx.compose.ui.graphics.Color

object AstroColors {
${colorLines.join("\n")}
}
`;

// AstroDimens.kt
const dimenLines = [];
let spacingCount = 0;
let radiusCount = 0;
for (const [group, counter] of [["space", () => spacingCount++], ["radius", () => radiusCount++]]) {
  for (const [tokenPath, names] of Object.entries(platformNames[group])) {
    if (names.android == null) continue;
    const node = getNode(tokenPath);
    if (node === undefined || node.$value === undefined) {
      throw new Error(`Token not found in tokens.json: ${tokenPath}`);
    }
    const px = pxToNumber(resolveValue(node.$value), tokenPath);
    dimenLines.push(`    val ${names.android}: Dp = ${px}.dp`);
    counter();
  }
}

const astroDimens = `${HEADER}package com.astro.design.tokens

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object AstroDimens {
${dimenLines.join("\n")}
}
`;

// AstroTypography.kt
const typographyLines = [];
let textStyleCount = 0;
for (const [tokenPath, names] of Object.entries(platformNames.text)) {
  if (names.android == null) continue;
  const node = getNode(tokenPath);
  if (node === undefined || node.$value === undefined) {
    throw new Error(`Token not found in tokens.json: ${tokenPath}`);
  }
  const style = node.$value;
  const fontSizeSp = pxToNumber(resolveValue(style.fontSize), `${tokenPath}.fontSize`);
  const lineHeightSp = pxToNumber(resolveValue(style.lineHeight), `${tokenPath}.lineHeight`);
  const fontWeight = resolveValue(style.fontWeight);
  if (!Number.isInteger(fontWeight)) {
    throw new Error(`Expected integer fontWeight for ${tokenPath}, got: ${fontWeight}`);
  }
  const letterSpacingSp = typeof names.androidLetterSpacingSp === "number"
    ? names.androidLetterSpacingSp
    : 0;
  typographyLines.push(
    `    val ${names.android}: AstroTextStyle = AstroTextStyle(\n` +
    `        fontSizeSp = ${fontSizeSp}.sp,\n` +
    `        lineHeightSp = ${lineHeightSp}.sp,\n` +
    `        fontWeight = ${fontWeight},\n` +
    `        letterSpacingSp = ${spLiteral(letterSpacingSp)}\n` +
    `    )`
  );
  textStyleCount++;
}

const astroTypography = `${HEADER}package com.astro.design.tokens

import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp

// Font-resource independent text style data. Map fontWeight to your own
// FontWeight and fontFamily at the call site.
data class AstroTextStyle(
    val fontSizeSp: TextUnit,
    val lineHeightSp: TextUnit,
    val fontWeight: Int,
    val letterSpacingSp: TextUnit
)

object AstroTypography {
${typographyLines.join("\n")}
}
`;

writeFileSync(join(outDir, "AstroColors.kt"), astroColors);
writeFileSync(join(outDir, "AstroDimens.kt"), astroDimens);
writeFileSync(join(outDir, "AstroTypography.kt"), astroTypography);

console.log(`AstroColors.kt: ${colorCount} colors (${colorSkipped} skipped, android name null)`);
console.log(`AstroDimens.kt: ${spacingCount} spacing + ${radiusCount} radius vals`);
console.log(`AstroTypography.kt: ${textStyleCount} text styles`);
console.log(`Output: ${outDir}`);
