#!/usr/bin/env node
// iOS token generator for the Astro cross-platform design system.
//
// Reads tokens/tokens.json (canonical token values) and
// tokens/platform-names.json (per-platform naming) and emits Swift
// source files into Sources/AstroDesignTokens/.
//
// Naming rules:
// - Swift symbols reuse the Android camelCase names, which are valid
//   Swift identifiers and keep the two mobile platforms aligned.
// - When the Android name is null (web-only tokens such as the
//   desktopMultiSelection and tagging groups) a lowerCamelCase name is
//   derived from the web name instead.
//
// Structure rule for colors: everything goes into one flat public enum
// AstroColor. The Android names are already flat and globally unique
// (primaryGalaxy8, btnPrimaryDefault, bgColorLight, ...), so nested
// enums would only add a level of indirection. Primitive palettes are
// emitted first, then semantic groups, each under a MARK comment.
// Semantic aliases like {color.neutral.2} are resolved to hex at
// generation time.
//
// Run from the repo root: node generators/ios.mjs
// Plain Node.js, no npm dependencies.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(
  readFileSync(join(repoRoot, "tokens", "tokens.json"), "utf8")
);
const platformNames = JSON.parse(
  readFileSync(join(repoRoot, "tokens", "platform-names.json"), "utf8")
);
const outDir = join(repoRoot, "Sources", "AstroDesignTokens");
mkdirSync(outDir, { recursive: true });

const HEADER = `// GENERATED FILE. Do not edit by hand.
// Generated by generators/ios.mjs from tokens/tokens.json and tokens/platform-names.json.
// Regenerate with: node generators/ios.mjs (run from the repo root).
`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tokenAtPath(path) {
  let node = tokens;
  for (const part of path.split(".")) {
    if (node == null || typeof node !== "object" || !(part in node)) {
      return undefined;
    }
    node = node[part];
  }
  return node;
}

// Resolves alias values like "{color.neutral.2}" to their concrete value,
// following chains and rejecting cycles.
function resolveValue(value, seen = new Set()) {
  if (typeof value === "string") {
    const match = value.match(/^\{(.+)\}$/);
    if (match) {
      const path = match[1];
      if (seen.has(path)) {
        throw new Error(`Alias cycle detected at ${path}`);
      }
      seen.add(path);
      const target = tokenAtPath(path);
      if (target === undefined || target.$value === undefined) {
        throw new Error(`Unresolvable alias: ${value}`);
      }
      return resolveValue(target.$value, seen);
    }
  }
  return value;
}

function hexLiteral(hex) {
  const match = /^#([0-9a-fA-F]{6})$/.exec(String(hex).trim());
  if (!match) {
    throw new Error(`Unsupported color format: ${hex}`);
  }
  return `0x${match[1].toUpperCase()}`;
}

function pxToNumber(dimension) {
  const match = /^(-?\d+(?:\.\d+)?)px$/.exec(String(dimension).trim());
  if (!match) {
    throw new Error(`Unsupported dimension format: ${dimension}`);
  }
  return Number(match[1]);
}

function num(value) {
  // Numbers in the token source are plain decimals; String() keeps them
  // exact (2 -> "2", -0.3 -> "-0.3").
  return String(value);
}

function lowerCamelFromWeb(webName) {
  const segments = String(webName)
    .split(/[^0-9A-Za-z]+/)
    .filter(Boolean);
  return segments
    .map((segment, index) =>
      index === 0
        ? segment.charAt(0).toLowerCase() + segment.slice(1)
        : segment.charAt(0).toUpperCase() + segment.slice(1)
    )
    .join("");
}

function swiftName(section, tokenPath) {
  const entry = platformNames[section] && platformNames[section][tokenPath];
  if (entry && entry.android) return entry.android;
  if (entry && entry.web) return lowerCamelFromWeb(entry.web);
  throw new Error(`No platform name found for ${tokenPath}`);
}

function writeGenerated(fileName, body) {
  writeFileSync(join(outDir, fileName), `${HEADER}\n${body}`, "utf8");
  console.log(`wrote Sources/AstroDesignTokens/${fileName}`);
}

// ---------------------------------------------------------------------------
// AstroColor.swift
// ---------------------------------------------------------------------------

function generateColors() {
  const lines = [];
  let count = 0;
  for (const [groupName, group] of Object.entries(tokens.color)) {
    lines.push(`    // MARK: ${groupName}`);
    lines.push("");
    for (const [key, token] of Object.entries(group)) {
      if (token == null || token.$type !== "color") continue;
      const tokenPath = `color.${groupName}.${key}`;
      const name = swiftName("color", tokenPath);
      const rawValue = token.$value;
      const hex = hexLiteral(resolveValue(rawValue));
      const isAlias = typeof rawValue === "string" && rawValue.startsWith("{");
      const comment = isAlias
        ? `// ${tokenPath} -> ${rawValue}`
        : `// ${tokenPath}`;
      lines.push(
        `    public static let ${name} = Color(astroHex: ${hex}) ${comment}`
      );
      count += 1;
    }
    lines.push("");
  }
  lines.pop();

  const body = `import SwiftUI

/// Astro design system color tokens.
///
/// All ${count} tokens live in this single flat namespace because the
/// canonical Android names are already flat and globally unique.
/// Primitive palettes (galaxy, nebula, neutral, sys and qd families)
/// come first, followed by semantic groups (buttons, backgrounds, text,
/// icons, strokes). Semantic aliases are resolved to hex values at
/// generation time, so every constant here is a concrete color.
public enum AstroColor {

${lines.join("\n")}
}
`;
  writeGenerated("AstroColor.swift", body);
  return count;
}

// ---------------------------------------------------------------------------
// ColorHex.swift
// ---------------------------------------------------------------------------

function generateColorHex() {
  const body = `import SwiftUI

extension Color {
    /// Creates an opaque sRGB color from a packed 24 bit 0xRRGGBB value.
    init(astroHex hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255.0,
            green: Double((hex >> 8) & 0xFF) / 255.0,
            blue: Double(hex & 0xFF) / 255.0,
            opacity: 1.0
        )
    }
}
`;
  writeGenerated("ColorHex.swift", body);
}

// ---------------------------------------------------------------------------
// AstroSpacing.swift and AstroRadius.swift
// ---------------------------------------------------------------------------

function generateDimensionEnum(fileName, enumName, docLine, sourceGroup, section, prefix) {
  const lines = [];
  let count = 0;
  for (const [key, token] of Object.entries(sourceGroup)) {
    if (token == null || token.$type !== "dimension") continue;
    const tokenPath = `${prefix}.${key}`;
    const name = swiftName(section, tokenPath);
    const value = pxToNumber(resolveValue(token.$value));
    lines.push(`    /// ${tokenPath} (${token.$value})`);
    lines.push(`    public static let ${name}: CGFloat = ${num(value)}`);
    count += 1;
  }

  const body = `import CoreGraphics

/// ${docLine}
public enum ${enumName} {
${lines.join("\n")}
}
`;
  writeGenerated(fileName, body);
  return count;
}

// ---------------------------------------------------------------------------
// AstroTypography.swift
// ---------------------------------------------------------------------------

const FONT_WEIGHT_MAP = {
  100: ".ultraLight",
  200: ".thin",
  300: ".light",
  400: ".regular",
  500: ".medium",
  600: ".semibold",
  700: ".bold",
  800: ".heavy",
  900: ".black",
};

function generateTypography() {
  const lines = [];
  let count = 0;
  for (const [groupName, group] of Object.entries(tokens.text)) {
    lines.push(`    // MARK: ${groupName}`);
    lines.push("");
    for (const [key, token] of Object.entries(group)) {
      if (token == null || token.$type !== "typography") continue;
      const tokenPath = `text.${groupName}.${key}`;
      const name = swiftName("text", tokenPath);
      const value = token.$value;
      const fontSize = pxToNumber(resolveValue(value.fontSize));
      const lineHeight = pxToNumber(resolveValue(value.lineHeight));
      const weightNumber = resolveValue(value.fontWeight);
      const weight = FONT_WEIGHT_MAP[weightNumber];
      if (!weight) {
        throw new Error(`Unmapped font weight ${weightNumber} at ${tokenPath}`);
      }
      const nameEntry = platformNames.text && platformNames.text[tokenPath];
      const letterSpacing =
        nameEntry && typeof nameEntry.androidLetterSpacingSp === "number"
          ? nameEntry.androidLetterSpacingSp
          : 0;
      lines.push(`    /// ${tokenPath}`);
      lines.push(
        `    public static let ${name} = AstroTextStyle(fontSize: ${num(fontSize)}, lineHeight: ${num(lineHeight)}, weight: ${weight}, letterSpacing: ${num(letterSpacing)})`
      );
      count += 1;
    }
    lines.push("");
  }
  lines.pop();

  const body = `import SwiftUI

/// A resolved Astro text style.
///
/// Sizes are in points. \`letterSpacing\` uses the Android sp value when
/// the token defines one (androidLetterSpacingSp) and 0 otherwise, so
/// it can be passed straight to \`.tracking(_:)\`.
public struct AstroTextStyle {
    public let fontSize: CGFloat
    public let lineHeight: CGFloat
    public let weight: Font.Weight
    public let letterSpacing: CGFloat

    public init(fontSize: CGFloat, lineHeight: CGFloat, weight: Font.Weight, letterSpacing: CGFloat) {
        self.fontSize = fontSize
        self.lineHeight = lineHeight
        self.weight = weight
        self.letterSpacing = letterSpacing
    }
}

/// Astro design system text style tokens.
public enum AstroTypography {

${lines.join("\n")}
}
`;
  writeGenerated("AstroTypography.swift", body);
  return count;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const colorCount = generateColors();
generateColorHex();
const spacingCount = generateDimensionEnum(
  "AstroSpacing.swift",
  "AstroSpacing",
  "Astro design system spacing tokens, in points.",
  tokens.space,
  "space",
  "space"
);
const radiusCount = generateDimensionEnum(
  "AstroRadius.swift",
  "AstroRadius",
  "Astro design system corner radius tokens, in points.",
  tokens.radius,
  "radius",
  "radius"
);
const textCount = generateTypography();

console.log(
  `done: ${colorCount} colors, ${spacingCount} spacing, ${radiusCount} radius, ${textCount} text styles`
);
